<?php

namespace Database\Seeders;

use App\Models\Domain;
use Illuminate\Database\Seeder;

class DomainConfigSeeder extends Seeder
{
    public function run(): void
    {
        $domainsConfig = [
            'pottydirect.com' => [
                'name' => 'Potty Direct',
                'business_name' => 'Potty Direct',
                'primary_keyword' => 'porta potty rental',
                'secondary_keywords' => [
                    // Urgency / speed (high intent)
                    'same day porta potty rental near me',
                    'same day portable toilet rental near me',
                    'emergency porta potty rental',
                    '24 hour porta potty rental',
                    'last minute porta potty rental',
                    'porta potty delivery today',
                    'portable toilet needed today',
                    'next day porta potty rental',

                    // Geo-targeted
                    'porta potty rental [city] [state]',
                    'portable toilet rental [city]',
                    'rent a porta potty in [city]',
                    'portable restroom rental [county]',
                    'local porta potty rental company',
                    'porta potty rental [city] same day',
                    'same day porta potty rental [city]',
                    'emergency porta potty rental [city]',
                    'portable toilet rental [city] [state]',
                    'affordable porta potty rental [city]',
                    'construction porta potty rental [city]',
                    'event porta potty rental [city]',
                    'luxury restroom trailer rental [city]',
                    'porta potty delivery [city]',
                    'rent a porta potty [city] today',
                    'dumpster rental [city]',
                    'septic tank pumping [city]',
                    'hand washing station rental [city]',
                    'portable shower rental [city]',
                    'temporary fence rental [city]',
                    'portable urinal rental [city]',
                    'hand wash trailer rental [city]',
                    'holding tank rental [city]',

                    // Construction / job site
                    'construction site porta potty rental',
                    'job site portable toilet rental',
                    'portable toilet for construction workers',
                    'portable restroom for work site',
                    'porta potty rental for contractors',
                    'OSHA portable toilet requirements',
                    'porta potty for job site near me',
                    'portable toilet service for construction site',
                    'high rise porta potty rental',
                    'temporary fence rental',

                    // Long-term / recurring
                    'monthly porta potty rental',
                    'long term porta potty rental',
                    'weekly porta potty rental',

                    // Events
                    'event porta potty rental near me',
                    'outdoor event restroom rental',
                    'party porta potty rental near me',
                    'porta potty rental for festival',
                    'outdoor concert restroom rental',
                    'portable toilet rental for sporting event',
                    'porta potty for outdoor wedding',
                    'porta potty for wedding reception',
                    'porta potty rental for graduation party',
                    'portable toilet rental for birthday party',
                    'portable restroom rental for family reunion',
                    'porta potty rental for fair',
                    'porta potty rental for 5k race',
                    'porta potty for marathon race',
                    'porta potty for golf tournament',
                    'temporary restroom rental for event',
                    'porta potty for tailgate party',
                    'porta potty for block party',
                    'porta potty for backyard party',
                    'porta potty for pool party',
                    'porta potty for farmers market',
                    'porta potty for street fair',
                    'porta potty for park event',
                    'porta potty for music festival',
                    'festival porta potty rental',
                    'outdoor wedding restroom rental',
                    'porta potty for open house',
                    'porta potty for school event',
                    'porta potty for church event',
                    'bathroom rentals for weddings',

                    // Luxury / upscale
                    'luxury restroom trailer rental',
                    'wedding restroom trailer rental',
                    'VIP restroom trailer rental',
                    'upscale porta potty rental',
                    'deluxe porta potty rental',
                    'restroom trailer rental for wedding near me',
                    'climate controlled restroom trailer rental',
                    'standard vs luxury porta potty cost',
                    'fancy porta potty rental',
                    'deluxe porta potty',

                    // Features
                    'flushing porta potty rental',
                    'portable bathroom rental with running water',
                    'ADA compliant porta potty rental',
                    'handicap porta potty rental near me',
                    'handicap accessible portable toilet rental',
                    'porta potty with sink rental',
                    'handwashing station rental near me',
                    'portable hand wash station rental',
                    'porta potty with hand sanitizer',
                    'porta potty rental with handwash station',
                    'solar powered portable toilet rental',
                    'portable restroom with lighting rental',
                    'eco friendly porta potty rental',
                    'odor control portable toilet rental',
                    'portable shower rental',
                    'portable urinal station rental',

                    // Cost / pricing
                    'how much does porta potty rental cost',
                    'porta potty rental cost',
                    'cost of porta potty',
                    'standard porta potty rental',
                    'porta potty rental price per day',
                    'porta potty delivery fee',
                    'affordable porta potty rental near me',
                    'affordable wedding restroom rental',
                    'porta potty rental weekly rate',
                    'porta potty rental monthly rate',
                    'porta potty rental quote',
                    'how much to rent a porta potty for a day',
                    'porta potty rental prices [city]',
                    'how many porta potties for 100 guests',
                    'how many porta potties for 50 guests',
                    'how many porta potties for 200 guests',
                    'do I need permit for porta potty rental',
                    'how early to book porta potty rental',
                    'what size porta potty do I need',
                    'porta potty rental contract',
                    'porta potty rental discount',
                    'luxury porta potty rental cost',
                    'porta potty trailer rental',

                    // Niche / role-based
                    'porta potty cleaning service',
                    'porta potty sanitization service',
                    'portable restroom pump out service',
                    'portable restroom for camping',
                    'porta potty camping',
                    'portable toilet for film set',
                    'porta potty for film crew',
                    'porta potty for property manager',
                    'porta potty for event coordinator',
                    'porta potty for wedding coordinator',
                    'event planner porta potty rental',
                    'portable restroom trailer',
                    'bathroom rentals',
                    'portable restroom rental near me',
                ],
                'primary_service' => 'porta potty',
                'service_types' => ['general', 'standard', 'deluxe', 'ada', 'construction', 'wedding', 'event', 'luxury', 'shower', 'mobile', 'vip', 'party', 'emergency', 'residential', 'portable', 'holding', 'sanitizer', 'dumpster', 'septic', 'portable-urinal', 'handwash-trailer', 'temporary-fencing', 'highrise'],
                'service_labels' => [
                    'general' => 'Standard Porta Potty Rental',
                    'standard' => 'Standard Porta Potty',
                    'deluxe' => 'Deluxe Flushable Porta Potty',
                    'ada' => 'ADA Accessible Porta Potty',
                    'construction' => 'Construction Site Porta Potty',
                    'wedding' => 'Wedding Event Porta Potty',
                    'event' => 'Event Porta Potty Rental',
                    'luxury' => 'Luxury Restroom Trailer',
                    'shower' => 'Portable Shower Unit',
                    'mobile' => 'Mobile Restroom Trailer',
                    'vip' => 'VIP Event Restroom',
                    'party' => 'Party Porta Potty Rental',
                    'emergency' => 'Emergency Porta Potty',
                    'residential' => 'Residential Porta Potty',
                    'portable' => 'Portable Porta Potty Rental',
                    'holding' => 'Holding Tank Rental',
                    'sanitizer' => 'Hand Sanitizer Station',
                    'dumpster' => 'Dumpster Rental',
                    'septic' => 'Septic Service',
                    'portable-urinal' => 'Portable Urinal Station',
                    'handwash-trailer' => 'Hand Wash Trailer',
                    'temporary-fencing' => 'Temporary Fencing & Barriers',
                    'highrise' => 'High-Rise Construction Toilet',
                ],
                'slug_prefix' => 'porta-potty',
                'tagline' => 'Same Day Porta Potty Rental — Serving Communities Across the USA',
                'cta_phone' => '+18336529344',
                'primary_color' => '#22C55E',
                'is_active' => true,
            ],
            'callaplumberusa.com' => [
                'name' => 'Plumbing Pro',
                'business_name' => 'Plumbing Pro',
                'primary_keyword' => 'plumbing services',
                'secondary_keywords' => [
                    // Geo-targeted service pages
                    'plumber [city] [state]',
                    'plumbing repair [city]',
                    'drain cleaning [city]',
                    'water heater replacement [city]',
                    'emergency plumber [city]',
                    'leak detection [city]',
                    'toilet repair [city]',
                    'faucet repair [city]',
                    'sump pump [city]',
                    'licensed plumber [city]',
                    'gas line repair [city]',
                    'kitchen drain clogged [city]',

                    // Emergency / urgent (high intent, low comp long-tail)
                    'burst pipe emergency repair cost',
                    'broken pipe water damage cleanup cost',
                    'sewer backup cleanup service near me',
                    'no hot water emergency fix cost',
                    'after hours plumber rates',
                    'overflowing toilet emergency plumber',
                    'weekend emergency plumber [city]',
                    'plumber open sunday [city]',

                    // Problem-specific symptom keywords (voice search ready)
                    'toilet keeps running after flush fix',
                    'toilet not flushing all the way fix',
                    'toilet leaking at base repair cost',
                    'gurgling drain when toilet flushes',
                    'banging pipes water hammer fix',
                    'smelly drain cleaning near me',
                    'slow draining shower repair',
                    'low water pressure in house diagnosis',
                    'sewer gas smell in basement fix',
                    'water heater pilot light wont stay lit',
                    'water heater making popping noise fix',
                    'water heater leaking from bottom repair',

                    // Cost / price keywords (highest conversion intent)
                    'drain cleaning cost 2025',
                    'water heater replacement cost by type',
                    'hydro jetting cost near me',
                    'sewer camera inspection cost',
                    'trenchless sewer lining cost',
                    'slab leak detection cost',
                    'sump pump replacement cost',
                    'backflow preventer installation cost',
                    'toilet replacement labor cost',
                    'plumber hourly rate [city]',
                    'plumbing estimate near me free',
                    'flat rate plumber [city]',

                    // Comparison keywords (information → conversion)
                    'tank vs tankless water heater cost',
                    'hydro jetting vs drain snaking',
                    'trenchless vs traditional sewer repair',
                    'water softener vs filtration system',

                    // Niche specific services
                    'kitchen sink pipe leak repair',
                    'bathtub drain clogged fix',
                    'shower drain hair clog removal cost',
                    'outdoor spigot leak repair cost',
                    'washing machine drain cleaning cost',
                    'garbage disposal not working fix',
                    'main drain line cleaning cost',
                    'water pressure regulator adjustment cost',
                    'floor drain cleaning service cost',
                    'shower valve replacement cost',
                    'toilet flange replacement cost',
                    'water line leak detection cost',
                    'whole house water filter installation cost',
                    'frozen pipe thawing service cost',
                    'polybutylene pipe replacement cost',
                    'galvanized pipe replacement cost',
                    'old house plumbing repair specialist',
                    'sewer line cleanout installation cost',
                    'first time home buyer plumbing inspection',
                    'home warranty plumbing claim help',
                    'plumber that accepts payment plans [city]',
                    'commercial plumbing maintenance contract',

                    // Seasonal / preventative (blog + service pages)
                    'frozen pipe prevention tips',
                    'spring plumbing maintenance checklist',
                    'winterize outdoor spigot cost',

                    // EEAT trust signals
                    'licensed bonded plumber [city]',
                    'plumber warranty work guarantee',
                    'plumbing financing [city]',
                ],
                'primary_service' => 'plumbing',
                'service_types' => [
                    'emergency',
                    'drain-cleaning',
                    'hydro-jetting',
                    'pipe-repair',
                    'leak-detection',
                    'slab-leak',
                    'water-heater',
                    'tankless-water-heater',
                    'sewer-line',
                    'trenchless-sewer',
                    'sewer-inspection',
                    'toilet-repair',
                    'faucet-repair',
                    'fixture-installation',
                    'garbage-disposal',
                    'gas-line',
                    'water-main',
                    'water-line',
                    'sump-pump',
                    'backflow-testing',
                    'water-filtration',
                    'water-softener',
                    'bathroom-remodel',
                    'kitchen-plumbing',
                    'commercial-plumbing',
                    'new-construction',
                    'septic',
                    'well-pump',
                    'pipe-thawing',
                    'radiant-heating',
                ],
                'service_labels' => [
                    'emergency' => '24/7 Emergency Plumbing',
                    'drain-cleaning' => 'Drain Cleaning Service',
                    'hydro-jetting' => 'Hydro Jetting Services',
                    'pipe-repair' => 'Pipe Repair & Replacement',
                    'leak-detection' => 'Leak Detection & Repair',
                    'slab-leak' => 'Slab Leak Detection & Repair',
                    'water-heater' => 'Water Heater Installation & Repair',
                    'tankless-water-heater' => 'Tankless Water Heater Services',
                    'sewer-line' => 'Sewer Line Repair & Replacement',
                    'trenchless-sewer' => 'Trenchless Sewer Repair',
                    'sewer-inspection' => 'Sewer Camera Inspection',
                    'toilet-repair' => 'Toilet Repair & Installation',
                    'faucet-repair' => 'Faucet & Fixture Repair',
                    'fixture-installation' => 'Fixture Installation & Replacement',
                    'garbage-disposal' => 'Garbage Disposal Services',
                    'gas-line' => 'Gas Line Installation & Repair',
                    'water-main' => 'Water Main Repair & Replacement',
                    'water-line' => 'Water Line Installation & Repair',
                    'sump-pump' => 'Sump Pump Installation & Repair',
                    'backflow-testing' => 'Backflow Prevention & Testing',
                    'water-filtration' => 'Water Filtration Systems',
                    'water-softener' => 'Water Softener Services',
                    'bathroom-remodel' => 'Bathroom Plumbing & Remodeling',
                    'kitchen-plumbing' => 'Kitchen Plumbing Services',
                    'commercial-plumbing' => 'Commercial Plumbing Services',
                    'new-construction' => 'New Construction Plumbing',
                    'septic' => 'Septic Tank Services',
                    'well-pump' => 'Well Pump Services',
                    'pipe-thawing' => 'Frozen Pipe Thawing & Repair',
                    'radiant-heating' => 'Radiant Heating Installation',
                ],
                'slug_prefix' => 'plumbing',
                'tagline' => '24/7 Emergency Plumbing Service — Serving Homes & Businesses Across the USA',
                'cta_phone' => '+18336529345',
                'primary_color' => '#273bd3',
                'secondary_color' => '#FF6B35',
                'is_active' => false,
            ],
        ];

        foreach ($domainsConfig as $domainName => $config) {
            $domain = Domain::updateOrCreate(
                ['domain' => $domainName],
                $config
            );

            $this->command->info($domain->wasRecentlyCreated
                ? "Created domain: {$config['name']}"
                : "Updated domain: {$config['name']}");
            $this->command->line('Service types: '.implode(', ', $config['service_types']));
        }

        $this->command->info('✅ All domains seeded successfully');
    }
}
