@extends(\App\Models\Domain::getLayoutPathStatic())
@section('title', 'Construction Porta Potty Rental | OSHA Compliant')
@section('meta_description', 'Construction site porta potty rental with OSHA-compliant units. Volume discounts for 5+ units, weekly servicing, and same-day delivery. Starting at $89/day.')
@section('canonical', route('construction.landing'))
@push('schema')
@php
$breadcrumbSchema = ['@context' => 'https://schema.org', '@type' => 'BreadcrumbList', 'itemListElement' => [['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => route('home')], ['@type' => 'ListItem', 'position' => 2, 'name' => 'Construction Site Porta Potty Rental', 'item' => route('construction.landing')]]];
$faqSchema = [
    "@context" => "https://schema.org",
    "@type" => "FAQPage",
    "mainEntity" => [
        ["@type" => "Question", "name" => "What are OSHA requirements for porta potties on construction sites?", "acceptedAnswer" => ["@type" => "Answer", "text" => "OSHA 1926.51(c) requires toilets be provided for employees. Ratio: 1 toilet per 20 workers. For 20 or fewer: 1 toilet. 20-40: 2 toilets. 40-60: 3 toilets. 60-80: 4 toilets. 80-100: 5 toilets. Over 100: 1 per 20."]],
        ["@type" => "Question", "name" => "How often are construction site porta potties serviced?", "acceptedAnswer" => ["@type" => "Answer", "text" => "Weekly servicing is included in standard rentals. We clean, pump, sanitize, and restock toilet paper and hand sanitizer every week. More frequent servicing available for active sites."]],
        ["@type" => "Question", "name" => "Can I get a discount for long-term construction projects?", "acceptedAnswer" => ["@type" => "Answer", "text" => "Yes! Long-term rentals (30+ days) qualify for additional discounts on top of volume pricing. Multi-month projects get our best rates. Call for a custom quote."]],
    ]
];
@endphp
<script type="application/ld+json">{!! json_encode($breadcrumbSchema, JSON_UNESCAPED_SLASHES) !!}</script>
<script type="application/ld+json">{!! json_encode($faqSchema, JSON_UNESCAPED_SLASHES) !!}</script>
@endpush
@section('content')
<section class="relative py-16 md:py-20 overflow-hidden bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
    <div class="relative max-w-4xl mx-auto px-4 sm:px-6 text-center">
        <nav class="flex items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm text-slate-400 mb-4">
            <a href="{{ route('home') }}" class="hover:text-white transition">Home</a>
            <x-icon name="chevron-right" class="w-3 h-3 sm:w-4 sm:h-4" />
            <span class="text-white">Construction Porta Potty Rental</span>
        </nav>
        <div class="inline-flex items-center gap-2 bg-orange-500/15 text-orange-400 text-sm font-bold px-4 py-2 rounded-full mb-5">
            <x-icon name="building" class="w-4 h-4" />
            CONSTRUCTION PORTA POTTY RENTAL
        </div>
        <h1 class="text-4xl md:text-5xl lg:text-6xl font-extrabold text-white mb-5">Construction Site Porta Potty Rental — <span class="text-orange-400">OSHA Compliant & Job-Site Ready</span></h1>
        <p class="text-xl text-slate-300 max-w-2xl mx-auto mb-8">Keep your construction site compliant and your crew productive. We deliver <strong class="text-white">OSHA-compliant porta potties starting at $89/day</strong> with weekly servicing, volume discounts, and same-day delivery for job sites nationwide.</p>
        <div class="flex flex-wrap justify-center gap-3 text-sm text-slate-300 mb-8">
            <span class="inline-flex items-center gap-1.5 bg-white/10 backdrop-blur px-4 py-2 rounded-full"><x-icon name="shield-check" class="w-4 h-4 text-emerald-400" />OSHA Compliant</span>
            <span class="inline-flex items-center gap-1.5 bg-white/10 backdrop-blur px-4 py-2 rounded-full"><x-icon name="truck" class="w-4 h-4 text-emerald-400" />Same-Day Delivery</span>
            <span class="inline-flex items-center gap-1.5 bg-white/10 backdrop-blur px-4 py-2 rounded-full"><x-icon name="cube" class="w-4 h-4 text-emerald-400" />Save Up to 35%</span>
        </div>
        <a href="tel:{{ domain_phone_raw() }}" class="inline-flex items-center gap-3 bg-amber-500 hover:bg-amber-400 text-white text-2xl font-bold py-5 px-10 rounded-full shadow-2xl shadow-amber-500/40 ring-4 ring-amber-400/30 transition-all hover:scale-[1.02] min-h-[44px]"><x-icon name="phone" class="w-7 h-7" />{{ domain_phone_display() }}</a>
    </div>
</section>
<section class="py-12 md:py-16 px-4 bg-white"><div class="max-w-4xl mx-auto"><h2 class="text-3xl font-bold text-slate-800 mb-6 text-center">Construction Site Options</h2>
<div class="grid md:grid-cols-3 gap-6">
<div class="bg-white border border-orange-200 rounded-2xl p-6 shadow-sm border-t-4 border-t-orange-500"><div class="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center mb-4"><x-icon name="building" class="w-6 h-6 text-orange-600" /></div><h3 class="font-bold text-lg mb-2">Standard Unit</h3><p class="text-emerald-600 font-bold text-xl mb-3">From $89/day</p><p class="text-slate-600 text-sm">OSHA-compliant, heavy-duty units with non-splash urinal, ventilation, and sanitizer dispenser. Weekly servicing included. Durable construction-grade materials.</p></div>
<div class="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm"><div class="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center mb-4"><x-icon name="water-drop" class="w-6 h-6 text-orange-600" /></div><h3 class="font-bold text-lg mb-2">Deluxe Unit</h3><p class="text-emerald-600 font-bold text-xl mb-3">From $150/day</p><p class="text-slate-600 text-sm">Flushing toilet with hand sink. Great for foreman offices and sites where workers spend all day. Includes mirror, lighting, and improved ventilation.</p></div>
<div class="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm"><div class="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center mb-4"><x-icon name="truck" class="w-6 h-6 text-orange-600" /></div><h3 class="font-bold text-lg mb-2">Construction Package</h3><p class="text-emerald-600 font-bold text-xl mb-3">Volume Pricing</p><p class="text-slate-600 text-sm">Multiple units with weekly servicing, OSHA docs, and on-site supervisor for large projects. Save up to 35% on 20+ units. Ideal for high-rise and infrastructure projects.</p></div>
</div></div></section>
<section class="py-12 md:py-16 px-4 bg-white"><div class="max-w-4xl mx-auto"><h2 class="text-3xl font-bold text-slate-800 mb-6 text-center">Why Contractors Choose Potty Direct</h2><div class="grid md:grid-cols-2 gap-6"><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="shield-check" class="w-5 h-5 text-orange-600" /></div><h3 class="font-bold text-slate-800 mb-2">OSHA Compliance Guaranteed</h3><p class="text-sm text-slate-600">All units meet OSHA standard 1926.51(c) for construction sanitation. Compliance documentation included with every rental. Avoid costly OSHA fines with proper restroom facilities.</p></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="cube" class="w-5 h-5 text-orange-600" /></div><h3 class="font-bold text-slate-800 mb-2">Volume & Long-Term Discounts</h3><p class="text-sm text-slate-600">Save 15% on 5-10 units, 25% on 11-20, and up to 35% on 20+. Long-term projects (30+ days) qualify for even deeper discounts. We work with general contractors on multi-year projects.</p></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="truck" class="w-5 h-5 text-orange-600" /></div><h3 class="font-bold text-slate-800 mb-2">Reliable Weekly Servicing</h3><p class="text-sm text-slate-600">Weekly cleaning, pumping, sanitizing, and restocking included. We never skip a service visit. If a unit needs attention between services, call us and we respond within 24 hours.</p></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="clock" class="w-5 h-5 text-orange-600" /></div><h3 class="font-bold text-slate-800 mb-2">Same-Day Delivery</h3><p class="text-sm text-slate-600">Order before 2PM for same-day delivery to your job site. Our fleet covers all 50 states with local drop-off. Need units for a emergency site opening? We can expedite.</p></div></div></div></section>
<section class="py-12 md:py-16 px-4 bg-slate-50"><div class="max-w-3xl mx-auto"><h2 class="text-3xl font-bold text-slate-800 mb-8 text-center">Construction Site FAQs</h2>
<div class="space-y-3">@php $faqs = [['q' => 'What are OSHA requirements for porta potties on construction sites?', 'a' => 'OSHA 1926.51(c) requires toilets be provided for employees. Ratio: 1 toilet per 20 workers. For 20 or fewer: 1 toilet. 20-40: 2 toilets. 40-60: 3 toilets. 60-80: 4 toilets. 80-100: 5 toilets. Over 100: 1 per 20.'], ['q' => 'How often are construction site porta potties serviced?', 'a' => 'Weekly servicing is included in standard rentals. We clean, pump, sanitize, and restock toilet paper and hand sanitizer every week. More frequent servicing available.'], ['q' => 'Can I get a discount for long-term construction projects?', 'a' => 'Yes! Long-term rentals (30+ days) qualify for additional discounts on top of volume pricing. Multi-month projects get our best rates. Call for a custom quote.']]; @endphp @foreach($faqs as $faq)<details class="bg-white border border-slate-200 rounded-xl shadow-sm hover:shadow-md transition-all group"><summary class="flex justify-between items-center p-5 cursor-pointer font-semibold text-slate-800 hover:text-orange-600 transition list-none"><span>{{ $faq['q'] }}</span><span class="text-2xl text-slate-400 group-open:rotate-45 group-open:text-orange-500 transition-all duration-300 ml-4 flex-shrink-0 bg-slate-100 w-8 h-8 rounded-full flex items-center justify-center">+</span></summary><div class="px-5 pb-5 text-slate-600 leading-relaxed"><p>{{ $faq['a'] }}</p></div></details>@endforeach</div></div></section>
@if(isset($testimonials) && $testimonials->isNotEmpty())
<section class="py-10 sm:py-12 md:py-16 px-3 sm:px-4 bg-slate-50"><div class="max-w-5xl mx-auto"><h2 class="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-8 sm:mb-10">What Our Customers Say</h2><div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">@foreach($testimonials as $t)<div class="bg-white border border-slate-200 p-4 sm:p-6 rounded-xl sm:rounded-2xl shadow-sm hover:shadow-lg transition-all"><div class="flex items-center gap-0.5 text-amber-400 mb-3 sm:mb-4" aria-label="{{ $t['rating'] }} out of 5 stars">@for($i = 0; $i < $t['rating']; $i++)<x-icon name="star" class="w-4 h-4 fill-current" />@endfor</div><p class="text-slate-700 mb-4 italic leading-relaxed text-sm sm:text-base">"{{ $t['content'] }}"</p><div class="flex items-center gap-3 pt-3 sm:pt-4 border-t border-slate-100"><div class="w-8 h-8 sm:w-9 sm:h-9 bg-gradient-to-br from-blue-500 to-blue-600 text-white rounded-full flex items-center justify-center font-bold text-xs sm:text-sm">{{ substr($t['customer_name'], 0, 1) }}</div><div><p class="font-bold text-sm text-slate-800">{{ $t['customer_name'] }}</p>@if(!empty($t['customer_title']))<p class="text-xs text-slate-500">{{ $t['customer_title'] }}</p>@endif</div></div></div>@endforeach</div></div></section>
@endif
<section class="py-16 md:py-20 px-4 bg-slate-900 text-white text-center"><div class="max-w-3xl mx-auto"><h2 class="text-3xl md:text-4xl font-bold mb-4">Keep your job site compliant</h2><p class="text-lg text-slate-400 mb-8">Call for volume pricing on construction site porta potties.</p><a href="tel:{{ domain_phone_raw() }}" class="inline-flex items-center gap-3 bg-amber-500 hover:bg-amber-400 text-white text-2xl font-bold py-5 px-10 rounded-full shadow-2xl shadow-amber-500/40 ring-4 ring-amber-400/30 transition-all hover:scale-[1.02] min-h-[44px]"><x-icon name="phone" class="w-7 h-7" />{{ domain_phone_display() }}</a></div></section>
<section class="py-12 md:py-16 px-4 bg-white border-t border-slate-100"><div class="max-w-4xl mx-auto text-center"><h2 class="text-2xl font-bold text-slate-800 mb-6">Related Resources</h2><div class="flex flex-wrap justify-center gap-4"><a href="{{ route('osha.guide') }}" class="bg-slate-100 hover:bg-orange-100 text-slate-700 hover:text-orange-700 font-medium px-5 py-2.5 rounded-full transition text-sm">OSHA Compliance Guide</a><a href="{{ route('comparison') }}" class="bg-slate-100 hover:bg-orange-100 text-slate-700 hover:text-orange-700 font-medium px-5 py-2.5 rounded-full transition text-sm">Unit Comparison</a><a href="{{ route('pricing') }}" class="bg-slate-100 hover:bg-orange-100 text-slate-700 hover:text-orange-700 font-medium px-5 py-2.5 rounded-full transition text-sm">Pricing Guide</a><a href="{{ route('calculator') }}" class="bg-slate-100 hover:bg-orange-100 text-slate-700 hover:text-orange-700 font-medium px-5 py-2.5 rounded-full transition text-sm">Units Calculator</a><a href="{{ route('how-many.page') }}" class="bg-slate-100 hover:bg-orange-100 text-slate-700 hover:text-orange-700 font-medium px-5 py-2.5 rounded-full transition text-sm">How Many Units</a><a href="{{ route('faq') }}" class="bg-slate-100 hover:bg-orange-100 text-slate-700 hover:text-orange-700 font-medium px-5 py-2.5 rounded-full transition text-sm">FAQ</a></div></div></section>
<div class="fixed bottom-4 left-4 right-4 md:hidden z-50"><a href="tel:{{ domain_phone_raw() }}" class="flex items-center justify-center gap-3 bg-gradient-to-r from-amber-500 to-amber-600 text-white font-bold text-lg py-4 px-6 rounded-2xl shadow-2xl shadow-amber-500/40 ring-4 ring-amber-400/30"><x-icon name="phone" class="w-6 h-6" /><span>Call for Site Pricing</span></a></div><div class="h-20 md:hidden"></div>
@endsection