@extends(\App\Models\Domain::getLayoutPathStatic())
@section('title', 'Festival Porta Potty Rental | High-Capacity Units')
@section('meta_description', 'Festival porta potty rental with high-capacity units for concerts, fairs & events. Volume discounts for 5+ units with same-day delivery. Free quote.')
@section('canonical', route('festival'))
@push('schema')
@php
$breadcrumbSchema = ['@context' => 'https://schema.org', '@type' => 'BreadcrumbList', 'itemListElement' => [['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => route('home')], ['@type' => 'ListItem', 'position' => 2, 'name' => 'Festival Porta Potty Rental', 'item' => route('festival')]]];
$faqSchema = [
    "@context" => "https://schema.org",
    "@type" => "FAQPage",
    "mainEntity" => [
        ["@type" => "Question", "name" => "What is the minimum number of porta potties required for a festival?", "acceptedAnswer" => ["@type" => "Answer", "text" => "General guideline: 1 unit per 50 attendees for 4-hour events. For multi-day festivals, plan 1 unit per 25 attendees. Always add ADA units — at least 1 per 20 standard units."]],
        ["@type" => "Question", "name" => "Do you deliver to festival venues across the USA?", "acceptedAnswer" => ["@type" => "Answer", "text" => "Yes, we deliver to festivals nationwide. Our fleet serves all 50 states with local delivery and setup. Same-day delivery available for orders before 2PM."]],
        ["@type" => "Question", "name" => "Can you service festival porta potties during the event?", "acceptedAnswer" => ["@type" => "Answer", "text" => "Absolutely. We offer on-site servicing during events to ensure clean, stocked restrooms throughout. Additional servicing can be scheduled as needed for high-traffic festivals."]],
    ]
];
@endphp
<script type="application/ld+json">{!! json_encode($breadcrumbSchema, JSON_UNESCAPED_SLASHES) !!}</script>
<script type="application/ld+json">{!! json_encode($faqSchema, JSON_UNESCAPED_SLASHES) !!}</script>
@endpush
@section('content')
<section class="relative py-16 md:py-20 overflow-hidden bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
    <div class="relative max-w-4xl mx-auto px-4 sm:px-6 text-center">
        <nav class="flex items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm text-slate-400 mb-4">
            <a href="{{ route('home') }}" class="hover:text-white transition">Home</a>
            <x-icon name="chevron-right" class="w-3 h-3 sm:w-4 sm:h-4" />
            <span class="text-white">Festival Porta Potty Rental</span>
        </nav>
        <div class="inline-flex items-center gap-2 bg-purple-500/15 text-purple-400 text-sm font-bold px-4 py-2 rounded-full mb-5">
            <x-icon name="music" class="w-4 h-4" />
            FESTIVAL PORTA POTTY RENTAL
        </div>
        <h1 class="text-4xl md:text-5xl lg:text-6xl font-extrabold text-white mb-5">Festival Porta Potty Rental — <span class="text-purple-400">High-Capacity for Large Crowds</span></h1>
        <p class="text-xl text-slate-300 max-w-2xl mx-auto mb-8">Keep your festival-goers comfortable with clean, reliable portable restrooms. We serve concerts, fairs, and large gatherings nationwide with <strong class="text-white">volume discounts for 5+ units</strong>.</p>
        <div class="flex flex-wrap justify-center gap-3 text-sm text-slate-300 mb-8">
            <span class="inline-flex items-center gap-1.5 bg-white/10 backdrop-blur px-4 py-2 rounded-full"><x-icon name="truck" class="w-4 h-4 text-emerald-400" />Free Delivery</span>
            <span class="inline-flex items-center gap-1.5 bg-white/10 backdrop-blur px-4 py-2 rounded-full"><x-icon name="cube" class="w-4 h-4 text-emerald-400" />Volume Discounts</span>
            <span class="inline-flex items-center gap-1.5 bg-white/10 backdrop-blur px-4 py-2 rounded-full"><x-icon name="sparkles" class="w-4 h-4 text-emerald-400" />Daily Servicing Available</span>
        </div>
        <a href="tel:{{ domain_phone_raw() }}" class="inline-flex items-center gap-3 bg-amber-500 hover:bg-amber-400 text-white text-2xl font-bold py-5 px-10 rounded-full shadow-2xl shadow-amber-500/40 ring-4 ring-amber-400/30 transition-all hover:scale-[1.02] min-h-[44px]"><x-icon name="phone" class="w-7 h-7" />{{ domain_phone_display() }}</a>
    </div>
</section>
<section class="py-12 md:py-16 px-4 bg-white"><div class="max-w-4xl mx-auto"><h2 class="text-3xl font-bold text-slate-800 mb-6 text-center">Festival Restroom Solutions</h2>
<div class="grid md:grid-cols-3 gap-6">
<div class="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm"><div class="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center mb-4"><x-icon name="building" class="w-6 h-6 text-purple-600" /></div><h3 class="font-bold text-lg mb-2">Standard Units</h3><p class="text-emerald-600 font-bold text-xl mb-3">From $89/day</p><p class="text-slate-600 text-sm">OSHA-compliant, durable units perfect for high-traffic festival use. Volume pricing available. Includes sanitizer dispenser and weekly servicing.</p></div>
<div class="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm"><div class="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center mb-4"><x-icon name="water-drop" class="w-6 h-6 text-purple-600" /></div><h3 class="font-bold text-lg mb-2">Deluxe Units</h3><p class="text-emerald-600 font-bold text-xl mb-3">From $150/day</p><p class="text-slate-600 text-sm">Flushing toilets with hand sinks. Ideal for VIP areas and family-friendly festival zones. Includes interior lighting and mirror.</p></div>
<div class="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm"><div class="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center mb-4"><x-icon name="accessibility" class="w-6 h-6 text-purple-600" /></div><h3 class="font-bold text-lg mb-2">ADA Units</h3><p class="text-emerald-600 font-bold text-xl mb-3">From $125/day</p><p class="text-slate-600 text-sm">Wheelchair-accessible units required for public events. Spacious interiors with grab bars, non-slip flooring, and 60" wide door.</p></div>
</div></div></section>
<section class="py-12 md:py-16 px-4 bg-white"><div class="max-w-4xl mx-auto"><h2 class="text-3xl font-bold text-slate-800 mb-6 text-center">Why Choose Potty Direct for Your Festival</h2><div class="grid md:grid-cols-2 gap-6"><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="truck" class="w-5 h-5 text-purple-600" /></div><h3 class="font-bold text-slate-800 mb-2">Nationwide Delivery</h3><p class="text-sm text-slate-600">We deliver to festivals across all 50 states. Our fleet handles everything from small local fairs to multi-day major festivals. Same-day delivery available for orders before 2PM.</p></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="cube" class="w-5 h-5 text-purple-600" /></div><h3 class="font-bold text-slate-800 mb-2">Volume Discounts</h3><p class="text-sm text-slate-600">Save big on large orders: 5-10 units save 15%, 11-20 units save 25%, 20+ units save up to 35%. Multi-day festivals qualify for additional long-term discounts.</p></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="sparkles" class="w-5 h-5 text-purple-600" /></div><h3 class="font-bold text-slate-800 mb-2">On-Site Servicing</h3><p class="text-sm text-slate-600">We can service units during your event to keep restrooms clean and stocked. Daily or twice-daily servicing available for high-traffic festivals with 500+ attendees.</p></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-6"><div class="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center mb-3"><x-icon name="shield-check" class="w-5 h-5 text-purple-600" /></div><h3 class="font-bold text-slate-800 mb-2">OSHA Compliant</h3><p class="text-sm text-slate-600">All units meet OSHA standards for public events. ADA units available for accessibility compliance. Documentation provided upon request.</p></div></div></div></section>
<section class="py-12 md:py-16 px-4 bg-slate-50"><div class="max-w-3xl mx-auto"><h2 class="text-3xl font-bold text-slate-800 mb-8 text-center">Festival Porta Potty FAQs</h2>
<div class="space-y-3">@php $faqs = [['q' => 'What is the minimum number of porta potties required for a festival?', 'a' => 'General guideline: 1 unit per 50 attendees for 4-hour events. For multi-day festivals, plan 1 unit per 25 attendees. Always add ADA units — at least 1 per 20 standard units.'], ['q' => 'Do you deliver to festival venues across the USA?', 'a' => 'Yes, we deliver to festivals nationwide. Our fleet serves all 50 states with local delivery and setup.'], ['q' => 'Can you service festival porta potties during the event?', 'a' => 'Absolutely. We offer on-site servicing during events to ensure clean, stocked restrooms throughout. Additional servicing can be scheduled as needed.']]; @endphp @foreach($faqs as $faq)<details class="bg-white border border-slate-200 rounded-xl shadow-sm hover:shadow-md transition-all group"><summary class="flex justify-between items-center p-5 cursor-pointer font-semibold text-slate-800 hover:text-purple-600 transition list-none"><span>{{ $faq['q'] }}</span><span class="text-2xl text-slate-400 group-open:rotate-45 group-open:text-purple-500 transition-all duration-300 ml-4 flex-shrink-0 bg-slate-100 w-8 h-8 rounded-full flex items-center justify-center">+</span></summary><div class="px-5 pb-5 text-slate-600 leading-relaxed"><p>{{ $faq['a'] }}</p></div></details>@endforeach</div></div></section>
@if(isset($testimonials) && $testimonials->isNotEmpty())
<section class="py-10 sm:py-12 md:py-16 px-3 sm:px-4 bg-slate-50"><div class="max-w-5xl mx-auto"><h2 class="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-8 sm:mb-10">What Our Customers Say</h2><div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">@foreach($testimonials as $t)<div class="bg-white border border-slate-200 p-4 sm:p-6 rounded-xl sm:rounded-2xl shadow-sm hover:shadow-lg transition-all"><div class="flex items-center gap-0.5 text-amber-400 mb-3 sm:mb-4" aria-label="{{ $t['rating'] }} out of 5 stars">@for($i = 0; $i < $t['rating']; $i++)<x-icon name="star" class="w-4 h-4 fill-current" />@endfor</div><p class="text-slate-700 mb-4 italic leading-relaxed text-sm sm:text-base">"{{ $t['content'] }}"</p><div class="flex items-center gap-3 pt-3 sm:pt-4 border-t border-slate-100"><div class="w-8 h-8 sm:w-9 sm:h-9 bg-gradient-to-br from-blue-500 to-blue-600 text-white rounded-full flex items-center justify-center font-bold text-xs sm:text-sm">{{ substr($t['customer_name'], 0, 1) }}</div><div><p class="font-bold text-sm text-slate-800">{{ $t['customer_name'] }}</p>@if(!empty($t['customer_title']))<p class="text-xs text-slate-500">{{ $t['customer_title'] }}</p>@endif</div></div></div>@endforeach</div></div></section>
@endif
<section class="py-16 md:py-20 px-4 bg-slate-900 text-white text-center"><div class="max-w-3xl mx-auto"><h2 class="text-3xl md:text-4xl font-bold mb-4">Planning a festival? We've got you covered.</h2><p class="text-lg text-slate-400 mb-8">Call for volume pricing on festival porta potty rentals.</p><a href="tel:{{ domain_phone_raw() }}" class="inline-flex items-center gap-3 bg-amber-500 hover:bg-amber-400 text-white text-2xl font-bold py-5 px-10 rounded-full shadow-2xl shadow-amber-500/40 ring-4 ring-amber-400/30 transition-all hover:scale-[1.02] min-h-[44px]"><x-icon name="phone" class="w-7 h-7" />{{ domain_phone_display() }}</a></div></section>
<section class="py-12 md:py-16 px-4 bg-white border-t border-slate-100"><div class="max-w-4xl mx-auto text-center"><h2 class="text-2xl font-bold text-slate-800 mb-6">Related Resources</h2><div class="flex flex-wrap justify-center gap-4"><a href="{{ route('comparison') }}" class="bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-700 font-medium px-5 py-2.5 rounded-full transition text-sm">Unit Comparison</a><a href="{{ route('pricing') }}" class="bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-700 font-medium px-5 py-2.5 rounded-full transition text-sm">Pricing Guide</a><a href="{{ route('calculator') }}" class="bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-700 font-medium px-5 py-2.5 rounded-full transition text-sm">Units Calculator</a><a href="{{ route('cost.page') }}" class="bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-700 font-medium px-5 py-2.5 rounded-full transition text-sm">Cost Guide</a><a href="{{ route('how-many.page') }}" class="bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-700 font-medium px-5 py-2.5 rounded-full transition text-sm">How Many Units</a><a href="{{ route('faq') }}" class="bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-700 font-medium px-5 py-2.5 rounded-full transition text-sm">FAQ</a></div></div></section>
<div class="fixed bottom-4 left-4 right-4 md:hidden z-50"><a href="tel:{{ domain_phone_raw() }}" class="flex items-center justify-center gap-3 bg-gradient-to-r from-amber-500 to-amber-600 text-white font-bold text-lg py-4 px-6 rounded-2xl shadow-2xl shadow-amber-500/40 ring-4 ring-amber-400/30"><x-icon name="phone" class="w-6 h-6" /><span>Call for Festival Pricing</span></a></div><div class="h-20 md:hidden"></div>
@endsection