<?php

return [
    'houston' => [
        'name' => 'Houston',
        'state' => 'TX',
        'neighborhoods' => 'Downtown, Uptown/Galleria, The Heights, Montrose, Midtown, Sugar Land, The Woodlands, Katy, Pearland, Cypress, Memorial, Bellaire, East End',
        'highways' => 'I-10 (Katy Freeway), I-45 (North Freeway/Gulf Freeway), I-69/US-59 (Southwest Freeway/Eastex Freeway), Beltway 8 (Sam Houston Tollway), Hardy Toll Road, Grand Parkway (SH 99), Westpark Tollway',
        'venues' => 'NRG Park (NRG Stadium), Minute Maid Park, Toyota Center, Discovery Green, The Woodlands Pavilion, Cynthia Woods Mitchell Pavilion, Pasadena Convention Center, George R. Brown Convention Center, Space Center Houston, Houston Livestock Show & Rodeo',
        'industries' => 'oil & gas, petrochemical (Houston Ship Channel), construction (master-planned communities), medical (Texas Medical Center — world\'s largest), port & logistics, energy (renewable + traditional), aerospace (NASA Johnson Space Center)',
        'weather' => 'Hot humid summers (90-100°F), hurricane season June-November, heavy rain/flood risk (Harris County flood control), mild winters (40-60°F). No freeze concerns except rare Arctic blasts.',
        'permits' => 'Harris County requires right-of-way permits for dumpster/porta potty placement in county roads. City of Houston requires building permits for construction sites over certain thresholds. No specific porta potty permit for private property, but public events need special event permits from Parks & Rec.',
        'construction' => 'Massive master-planned communities (Bridgeland, Cinco Ranch, Sienna). I-45 widening project. Commercial construction booming in The Woodlands and Katy. Heavy highway/infrastructure projects along Grand Parkway.',
    ],
    'dallas' => [
        'name' => 'Dallas',
        'state' => 'TX',
        'neighborhoods' => 'Uptown, Deep Ellum, Bishop Arts District, Knox-Henderson, Mockingbird Station, Oak Lawn, Highland Park, University Park, Las Colinas (Irving), Addison, Plano, Frisco, McKinney, Garland, Richardson',
        'highways' => 'I-35E (Stemmons Freeway), I-30 (Tom Landry Freeway), I-635 (LBJ Freeway), US-75 (Central Expressway), Dallas North Tollway, President George Bush Turnpike (SH 190), Sam Rayburn Tollway (SH 121), DFW Connector',
        'venues' => 'AT&T Stadium (Arlington), Cotton Bowl, American Airlines Center, Toyota Stadium (Frisco), Globe Life Field, Texas Motor Speedway, Fair Park (State Fair of Texas), Kay Bailey Hutchison Convention Center, Gilley\'s Dallas, Southfork Ranch',
        'industries' => 'telecommunications (AT&T, Verizon), technology (Texas Instruments), banking (Comerica, Texas Capital), insurance (Liberty Mutual), defense (Lockheed Martin in Fort Worth), logistics (DFW Airport — 2nd busiest), construction (north Dallas suburbs explosive growth)',
        'weather' => 'Hot summers (95-105°F), tornado season March-May, ice storms December-February, hailstorms frequent in spring. DFW is in "Tornado Alley" — severe weather awareness is critical.',
        'permits' => 'City of Dallas requires tree removal permits that can affect site prep. Frisco/Plano require encroachment permits for equipment on public right-of-way. Event permits needed for street closures. Collin County has specific rules for rural construction sites.',
        'construction' => 'Explosive growth in Frisco, McKinney, Celina (one of fastest-growing US cities). Uptown Dallas high-rise boom. I-635 managed lanes project. Legacy West development (Plano). Highway expansion along North Dallas Tollway extension.',
    ],
    'los-angeles' => [
        'name' => 'Los Angeles',
        'state' => 'CA',
        'neighborhoods' => 'Downtown (DTLA), Hollywood, Santa Monica, Venice Beach, Beverly Hills, Silver Lake, Echo Park, Pasadena, Long Beach, Burbank, Glendale, Sherman Oaks, Van Nuys, West Hollywood, Marina del Rey, San Pedro',
        'highways' => 'I-5 (Golden State Freeway/Santa Ana Freeway), US-101 (Hollywood Freeway/Ventura Freeway), I-405 (San Diego Freeway — notoriously congested), I-10 (Santa Monica Freeway/San Bernardino Freeway), CA-110 (Harbor Freeway/Pasadena Freeway — oldest in LA), CA-91 (Artesia Freeway), CA-60 (Pomona Freeway), I-605 (San Gabriel River Freeway)',
        'venues' => 'SoFi Stadium, Dodger Stadium, Crypto.com Arena, Hollywood Bowl, Rose Bowl (Pasadena), Los Angeles Convention Center, LA Coliseum, Santa Monica Pier, Universal Studios Hollywood, Disneyland (Anaheim), Griffith Park, Exposition Park',
        'industries' => 'entertainment (film/TV/music — Hollywood), technology (Silicon Beach), aerospace (El Segundo, Palmdale), logistics (Port of LA/Long Beach — busiest in US), tourism, construction (mixed-use TOD transit projects), health/wellness',
        'weather' => 'Mediterranean climate — mild year-round (60-85°F). Dry summers (May-October), light rain December-March. Wildfire risk in hills (Santa Ana winds Oct-Nov). Earthquake preparedness required. No snow or freeze issues in basin.',
        'permits' => 'California Title 24 building codes apply (one of strictest). Coastal Commission permits needed near beaches. LA City requires film/event permits with porta potty provisions. AQMD (air quality) rules for diesel equipment on construction sites. Cal/OSHA enforces strict sanitation ratios.',
        'construction' => 'Massive transit projects (LA Metro Purple Line extension, Crenshaw/LAX line). Mixed-use TOD projects near rail stations. ADU (accessory dwelling unit) boom in backyards. High-rise residential in DTLA. I-405 Sepulveda Pass improvements. Film production construction (sets/stages).',
    ],
    'new-york-city' => [
        'name' => 'New York City',
        'state' => 'NY',
        'neighborhoods' => 'Manhattan (Upper East Side, Upper West Side, Midtown, Chelsea, SoHo, Greenwich Village, East Village, Lower East Side, Financial District, Harlem, Washington Heights), Brooklyn (Williamsburg, Park Slope, Bushwick, DUMBO), Queens (Astoria, Long Island City, Flushing), Bronx, Staten Island',
        'highways' => 'I-95 (Cross Bronx Expressway/New England Thruway — most congested in US), I-278 (BQE/Brooklyn-Queens Expressway/Gowanus Expressway), FDR Drive (East Side), West Side Highway/Henry Hudson Parkway, I-495 (Long Island Expressway), I-678 (Van Wyck Expressway/Grand Central Parkway), Belt Parkway, Jackie Robinson Parkway, Staten Island Expressway (I-278), RFK/Triborough Bridge, Verrazzano-Narrows Bridge, Holland/Lincoln Tunnels',
        'venues' => 'Madison Square Garden, Yankee Stadium, Citi Field, Barclays Center, MetLife Stadium (NJ), Central Park (Great Lawn, SummerStage), Prospect Park, Jacob Javits Convention Center, Lincoln Center, Radio City Music Hall, Broadway theaters, Arthur Ashe Stadium (US Open)',
        'industries' => 'finance (Wall Street), media/publishing, technology (Silicon Alley), real estate/construction, healthcare (world\'s largest medical complex), education, tourism (60M+ annual visitors), fashion, legal, advertising',
        'weather' => 'Four distinct seasons. Hot humid summers (80-95°F), cold winters (20-40°F with snow/ice storms), nor\'easters October-April. Spring/fall mild. Snow removal is a major operational factor. Hurricane risk (Sandy 2012, Ida 2021).',
        'permits' => 'NYC Department of Buildings (DOB) strict permitting for construction. NYCDOT requires street obstruction permits for equipment. Special event permits from NYC Parks and Mayor\'s Office. MTA permits for construction near transit. Environmental review (CEQR) for large projects. Sanitation requirements for public events.',
        'construction' => 'Constant high-rise development. East Side Access (LIRR to Grand Central). Second Avenue Subway Phase 2. Moynihan Train Hall expansion. Brooklyn Navy Yard redevelopment. Hudson Yards continues development. LaGuardia Airport reconstruction. Citywide scaffolding/scaffold law (Local Law 126).',
    ],
    'miami' => [
        'name' => 'Miami',
        'state' => 'FL',
        'neighborhoods' => 'Downtown Miami, Brickell, South Beach, Coral Gables, Coconut Grove, Key Biscayne, Wynwood, Design District, Little Havana, Midtown, Edgewater, Doral, Hialeah, Kendall, Homestead, Aventura, Sunny Isles Beach',
        'highways' => 'I-95 (Dolphin Expressway connection), I-195 (Julia Tuttle Causeway), I-395 (MacArthur Causeway), FL-826 (Palmetto Expressway), FL-836 (Dolphin Expressway — to Miami International Airport), FL-112 (Airport Expressway), FL-874 (Don Shula Expressway), US-1 (Biscayne Boulevard), Turnpike Extension (Homestead Extension), Rickenbacker Causeway (to Key Biscayne)',
        'venues' => 'Hard Rock Stadium (Miami Dolphins), Kaseya Center (Miami Heat), loanDepot Park (Marlins), Miami Beach Convention Center, Bayfront Park, American Airlines Arena, Jungle Island, Zoo Miami, Coconut Grove Convention Center, Perez Art Museum (PAMM), FTX Arena, Marlins Park',
        'industries' => 'tourism/hospitality (cruise capital of the world — Port Miami), international banking/finance, real estate (luxury condos), healthcare (Jackson Health, Baptist Health), tech (Wynwood startup hub), creative/marketing, aviation (MIA — major LATAM gateway), construction',
        'weather' => 'Subtropical — hot humid summers (85-95°F), mild winters (60-80°F). Hurricane season June-November (peak Aug-Oct). Heavy afternoon thunderstorms May-October (sea breeze). Flood risk in low-lying areas. King tides Sept-November. No freeze issues.',
        'permits' => 'Miami-Dade County has strict hurricane building codes (post-Andrew). Flood zone permits required for equipment placement in certain areas (FEMA flood maps). Special event permits needed for beach/parks events. Miami Beach has noise ordinances affecting night work. Sea level rise considerations for new construction in low-elevation zones.',
        'construction' => 'Brickell high-rise condo boom continues. Downtown Miami office/residential growth. Wynwood redevelopment (art/tech hub). Miami Worldcenter project. Brightline station developments. I-95 express lanes expansion. Port Miami tunnel maintenance. Rising sea level drives elevated construction methods.',
    ],
    'chicago' => [
        'name' => 'Chicago',
        'state' => 'IL',
        'neighborhoods' => 'The Loop, River North, Lincoln Park, Wicker Park, Logan Square, Lakeview, Wrigleyville, Gold Coast, Hyde Park, Pilsen, Little Italy, Chinatown, Bucktown, Andersonville, Bronzeville, West Loop, Fulton Market District, South Loop',
        'highways' => 'I-90/I-94 (Kennedy Expressway/Edens Expressway/Dan Ryan Expressway), I-290 (Eisenhower Expressway), I-55 (Stevenson Expressway), I-57, Lake Shore Drive (US-41 — lakefront), I-294 (Tri-State Tollway), I-88 (Ronald Reagan Tollway), I-355 (Veterans Memorial Tollway), Chicago Skyway (I-90 toll bridge), Bishop Ford Freeway (I-94)',
        'venues' => 'Soldier Field, Wrigley Field, United Center, Guaranteed Rate Field, McCormick Place Convention Center (largest in North America), Navy Pier, Millennium Park (Pritzker Pavilion), Grant Park (Lollapalooza), Northerly Island, Arie Crown Theater, Wintrust Arena, Allstate Arena (Rosemont)',
        'industries' => 'finance (CME Group/Chicago Board of Trade, futures exchanges), manufacturing, logistics (rail hub — O\'Hare 2nd busiest airport), technology (Google/McDonald\'s HQ), healthcare (Northwestern Medicine, Rush), education (UChicago, Northwestern), food processing, insurance',
        'weather' => 'Extreme seasonal variation. Hot humid summers (80-95°F). Bitter cold winters (0-30°F with polar vortex events, lake-effect snow). Snow accumulation up to 40" annually. Spring severe storms/tornado risk. Lake Michigan creates microclimates (lake-effect snow, cooler summers near shore).',
        'permits' => 'City of Chicago requires building permits including porta potty placement for construction sites (Chicago Municipal Code). Street occupancy permits for equipment on public way. Special events require Mayor\'s Office of Special Events permit with sanitation plan. Chicago Park District permits for events in parks. Cook County has separate requirements.',
        'construction' => 'Massive O\'Hare expansion (terminal renovation). Lincoln Yards mega-development. The 78 mixed-use development. Chicago Riverwalk extension. Lake Shore Drive reconstruction planning. Red Line Extension project. Fulton Market continuous redevelopment. High-rise residential in West Loop.',
    ],
    'phoenix' => [
        'name' => 'Phoenix',
        'state' => 'AZ',
        'neighborhoods' => 'Downtown Phoenix, Arcadia, Paradise Valley, Scottsdale (Old Town, North Scottsdale), Tempe, Mesa, Chandler, Gilbert, Glendale, Peoria, Surprise, Goodyear, Buckeye, Cave Creek, Ahwatukee Foothills',
        'highways' => 'I-10 (Maricopa Freeway/Papago Freeway), I-17 (Black Canyon Freeway), US-60 (Superstition Freeway), AZ-101 (Loop 101 — Agua Fria Freeway/Pima Freeway), AZ-202 (Loop 202 — San Tan Freeway/South Mountain Freeway), AZ-51 (Piestewa Freeway), AZ-143 (Hohokam Expressway), I-17 to Flagstaff route',
        'venues' => 'State Farm Stadium (Glendale — Cardinals/events), Chase Field (Diamondbacks), Footprint Center (Suns/Mercury), Phoenix Raceway, Phoenix Convention Center, Mesa Amphitheatre, Ak-Chin Pavilion, Talking Stick Resort Amphitheatre, Desert Botanical Garden, WestWorld of Scottsdale, Coconino County Fairgrounds',
        'industries' => 'construction (fastest-growing metro), semiconductor manufacturing (TSMC, Intel), healthcare (Mayo Clinic, Banner Health), aerospace (Honeywell, Boeing), technology (Uber, Yelp ops centers), tourism (golf, resorts), agriculture (cotton, citrus — decreasing), logistics (distribution hub)',
        'weather' => 'Extreme heat — summer 105-120°F (May-September). Monsoon season June-September (dust storms/haboobs, flash flooding). Mild winters (60-80°F) — peak construction season. Virtually no rain Oct-May. Heat safety is critical (hydration schedules, shade requirements for workers). No snow/freeze issues.',
        'permits' => 'Arizona OSHA (ADOSH) enforces heat safety rules (mandatory shade/water breaks above 85°F). City of Phoenix requires permits for construction site equipment placement. Maricopa County flood control district permits for sites in floodplains. Scottsdale has strict aesthetics requirements for equipment visible from roads. Event permits from individual cities.',
        'construction' => 'Fastest-growing metro in US. Massive master-planned communities (Douglas Ranch, Teravalis). TSMC semiconductor fab construction in north Phoenix. I-10 widening (South Mountain Freeway completion). Semiconductor supplier ecosystem buildout. Buckeye/Goodyear explosive residential growth.',
    ],
    'atlanta' => [
        'name' => 'Atlanta',
        'state' => 'GA',
        'neighborhoods' => 'Buckhead, Midtown, Downtown, Virginia-Highland, Decatur, East Atlanta Village, Old Fourth Ward, Inman Park, Candler Park, Grant Park, West Midtown, Castleberry Hill, Alpharetta, Marietta, Roswell, Sandy Springs, Brookhaven, Smyrna, Duluth',
        'highways' => 'I-75/85 (Downtown Connector — most congested in Georgia), I-285 (Perimeter — infamous for traffic), I-20 (East-West), GA-400 (North Atlanta), I-85 North (to Greenville/Charlotte), I-75 South (to Macon/Florida), GA-316 (to Athens/Lawrenceville), US-78 (Stone Mountain Freeway), GA-92, GA-120',
        'venues' => 'Mercedes-Benz Stadium, Truist Park (Braves — Cobb County), State Farm Arena (Hawks/Hot), Georgia World Congress Center, Philips Arena, Lakewood Amphitheatre, Chastain Park Amphitheatre, Piedmont Park (Music Midtown, festivals), Centennial Olympic Park, Atlanta Motor Speedway (Hampton), Zoo Atlanta, Cobb Galleria Centre',
        'industries' => 'logistics (world\'s busiest airport — ATL, Hartsfield-Jackson), entertainment (film/TV — "Hollywood of the South," Tyler Perry Studios, Trilith), technology (Microsoft, Google, Apple growing presence), finance (Bank of America, Truist, NCR), healthcare (Emory, CDC HQ — main campus), education (Georgia Tech, Emory, Georgia State), construction (data center boom)',
        'weather' => 'Humid subtropical. Hot summers (85-95°F). Some afternoons thunderstorms. Mild winters (35-55°F) — occasional ice/snow events that shut down the city. Spring severe storms and tornado risk. Pollen season (February-May — highest in US). Occasional tropical storm remnants.',
        'permits' => 'GDOT permits needed for equipment near state highways. City of Atlanta requires building permits and may require sanitation plans for large events. MARTA permits for work near transit. Fulton County and Dekalb County have separate requirements. Tree protection ordinances in Atlanta (must preserve certain trees).',
        'construction' => 'Data center construction boom (Douglas County, Newton County). Film studio construction (Trilith, Assembly Yards). I-285/I-20 interchange reconstruction. MARTA expansion and transit-oriented development. Battery Atlanta development (Truist Park area). Single-family home construction in suburbs. Old Fourth Ward and Westside BeltLine redevelopment.',
    ],
    'denver' => [
        'name' => 'Denver',
        'state' => 'CO',
        'neighborhoods' => 'LoDo (Lower Downtown), RiNo (River North), Capitol Hill, Cherry Creek, Highlands, Five Points, Union Station, Washington Park, Golden Triangle, South Pearl Street, Baker, Congress Park, Stapleton, Aurora, Lakewood, Englewood, Littleton, Centennial',
        'highways' => 'I-25 (Valley Highway/Denver-Boulder Turnpike — main north-south), I-70 (East-West through mountains — critical for ski traffic), US-36 (Boulder Turnpike), I-225 (Aurora), C-470 (South suburban beltway), E-470 (Toll road — eastern beltway), CO-93 (Golden-Boulder), US-285 (to southwest), CO-119 (Boulder-Denver via Diagonal Highway)',
        'venues' => 'Empower Field at Mile High (Broncos), Coors Field (Rockies), Ball Arena (Nuggets/Avalanche), Denver Coliseum, Red Rocks Amphitheatre (Morrison — iconic), Denver Performing Arts Complex, Colorado Convention Center, National Western Complex, Elitch Gardens, Civic Center Park, Bishop Castle, Dick\'s Sporting Goods Park (Commerce City — Rapids)',
        'industries' => 'energy (oil & gas — DCPA/DJ Basin, renewable — NREL nearby), aerospace (United Launch Alliance, Sierra Space), technology (Salesforce, Google, Amazon, Palantir), cannabis (recreational), healthcare, outdoor recreation (REI HQ in nearby), construction (population growth), brewing (Sam Adams, Coors, hundreds of craft breweries)',
        'weather' => 'Semi-arid — 300+ days of sunshine. Hot summers (85-95°F). Snow season October-May (but snow melts fast — intense sun). Average 57" snow annually. Afternoon thunderstorms with lightning common in summer (halts outdoor work). March is snowiest month. Chinook winds cause rapid temperature swings. Hail risk May-August.',
        'permits' => 'Colorado OSHA enforces rules including heat/cold stress. Denver requires building permits for structures, construction site permits. RTD/Front Range permits for work near transit. Jefferson County has strict grading permits. Special event permits from Denver Parks & Rec. Marijuana industry creates unique event sanitation needs (long-duration festivals).',
        'construction' => 'Massive population growth driving residential construction. I-25 North Express Lanes expansion. Denver International Airport (DIA) — 3rd busiest, large hotel/transit expansions. RiNo warehouse-to-office conversions. National Western Center redevelopment. Housing in Aurora and Denver suburbs. Mountain-area construction (Eagle County, Summit County drive summer demand).',
    ],
    'seattle' => [
        'name' => 'Seattle',
        'state' => 'WA',
        'neighborhoods' => 'Capitol Hill, Ballard, Fremont, Green Lake, Queen Anne, First Hill, Belltown, South Lake Union, Pioneer Square, International District, Georgetown, West Seattle, Beacon Hill, University District, Wallingford, Madrona, Redmond, Bellevue (Eastside), Kirkland, Issaquah, Shoreline, Renton, Tacoma',
        'highways' => 'I-5 (main north-south — through downtown Seattle), I-405 (Eastside — notoriously congested), SR-520 (Evergreen Point Floating Bridge — to Redmond, toll), SR-99 (Alaskan Way Viaduct — mostly replaced by tunnel), I-90 (to Bellevue, across Lake Washington floating bridge), SR-167 (Kent Valley/Puyallup), SR-509 (Airport/Duwamish), I-705 (Tacoma — to I-5)',
        'venues' => 'Lumen Field (Seahawks/Sounders), T-Mobile Park (Mariners), Climate Pledge Arena (Kraken/concerts), Seattle Convention Center (Arch + Summit buildings), WaMu Theater, McCaw Hall, Paramount Theatre, Chateau Ste. Michelle (Woodinville), Marymoor Park (Redmond), The Gorge Amphitheatre (George — 2hrs east), Washington State Fair (Puyallup)',
        'industries' => 'technology (Microsoft, Amazon, Google, Meta engineering offices), aerospace (Boeing — Everett assembly plant, world\'s largest building), healthcare (Fred Hutch, UW Medicine), gaming (Valve, Nintendo of America), biotech, logistics (Port of Seattle — container + cruise), coffee (Starbucks HQ, local roasters), outdoor retail (REI HQ)',
        'weather' => 'Maritime — moderate temps year-round. Cool summers (65-80°F). Rainy Nov-March (overcast, 40-50°F). Snow rare but disruptive (1-2 events/year, shuts down city). Spring/fall pleasant. Limited extreme heat. "Atmospheric rivers" cause flooding. Wildfire smoke Aug-Sept (from Eastern WA/BC). No real freeze issues for most of year.',
        'permits' => 'Washington State requires prevailing wage for public works. Seattle Department of Construction & Inspections (SDCI) strict permitting. Sound Transit permits for work near light rail. City of Seattle street use permits for equipment on right-of-way. Environmental review (SEPA) for large projects. Salmon-safe construction practices required near waterways. King County has separate permitting.',
        'construction' => 'Amazon HQ expansion (now on hold/reducing but built massive). Sound Transit light rail expansion (Eastside Link through Bellevue/Redmond). Alaskan Way Viaduct replacement tunnel completed — new waterfront projects. SR-520 bridge replacement program (Montlake lid). Mixed-use development in Ballard, Capitol Hill. Boeing 737 Max production ramp in Everett. Microsoft campus modernization in Redmond.',
    ],
];
